### ISSUE TITLE
Add callback conversion

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/MoqToNSubstituteConverter#12]
> Moq:
> 
> ```cs
> int? capturedArg = null;
> 
> mock
>   .Setup(x => x.MyMethod(It.IsAny<int>(), It.IsAny<string>()))
>   .Returns(true)
>   .Callback((int i, string s) => capturedArg = i);
> ```
> 
> NSubstitute:
> 
> ```cs
> int? capturedArg = null;
> 
> substitute
>   .MyMethod(Arg.Do<int>(i => capturedArg = i), Arg.Any<string>())
>   .Returns(true);
> ```

**Comment by yor-so** [comment]
I'm not sure if this also should cover exceptions, since they are done using callbacks for void methods:
https://nsubstitute.github.io/help/throwing-exceptions/

moq:
`mock(x => x.Method(It.IsAny<int>())).Throws<Exception>();`

NSubstitute:
`mock.When(x => x.Method(Arg.Any<int>())).Do(call => { throw new Exception(); });`

I'm not great with regex but I'll try to work on it if I have the time. I'll also open an issue in Alberto's repo, in case someone there can help: https://github.com/AlbertoMonteiro/moq-to-nsubstitute

**Comment by samsmithnz** [comment]
Agree it should cover exceptions. I'm terrible with Regex, try to avoid it where possible. Will continue to chip away at this one.
